Sprint 4
snowsergo/MovieQuiz-ios pull request #5
Opened 2022-08-02 20:02 UTC by snowsergo

Сделал базовую верстку и логику на мок данных

2022-08-03 08:16 UTC, ABashkirova requested changes
Привет, Сергей! 

Оставляю несколько предложений по исправлению к кода. Замечания по верстке найдешь на платформе.

2022-08-03 08:16 UTC, ABashkirova commented on MovieQuiz/AppDelegate.swift
> +        sleep(1)
Я думаю, в этой задаче этот код лишний.

2022-08-03 08:16 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    private var rigthAnswerCount: Int = 0
```suggestion
    private var rightAnswerCount: Int = 0
```

2022-08-03 08:16 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    }
```suggestion
    }
    
```

2022-08-03 08:16 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    static var ypGreen: UIColor { UIColor(named: "YP Green")! }
Давайте перенесем этот код в файл`UIColor+Extensions`

2022-08-03 08:16 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    private var currentQuestionIndex: Int = 0
```suggestion
    }
    
    private var currentQuestionIndex: Int = 0
```

2022-08-03 08:16 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +          print("OK button is clicked!")
```suggestion
```

Лишний отладочный код стоит удалять

2022-08-03 08:16 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        self.present(alert, animated: true, completion: nil)
```suggestion
        present(alert, animated: true, completion: nil)
```

swift лаконичный язык, когда можно использовать конструкцию проще - следует использовать ее. В данном случае self избыточен.

2022-08-03 08:16 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    private func convert(model: QuizeQuestion) -> QuizeStepViewModel {
На мой взгляд, достояно сложно будет догадаться **во что именно конвертируем** по такому называнию в момент вызова:

`showStep(quize: convert(model: questions[currentQuestionIndex]))`

Эта функция создает модель шага из модели вопроса. 
Предлагаю назвать так: `func createStepModel(from model: QuizeQuestion) -> QuizeStepViewModel`

2022-08-03 08:16 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        imageView.layer.masksToBounds = true
Свойства `masksToBounds` и `cornerRadius` можно применить один раз, ведь у нас всегда один и тот же радиус сгругления :)

2022-08-03 08:16 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        imageView.layer.masksToBounds = true
Из комментария выше, получается эта строчка лишняя

2022-08-08 17:46 UTC, ABashkirova reviewed
Отлично, задача принята! 

Вы можете доработать проект по предложенным правкам.

2022-08-08 17:46 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    @IBOutlet weak var questionLabel: UILabel!
Модификатор доступа нужен приватный

2022-08-08 17:46 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    private func getResultMessage() -> String {
```suggestion
    }
    
    private func getResultMessage() -> String {
```

2022-08-08 17:46 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        formater.dateFormat = "dd.MM.yyyy hh:mm"
Вы можете использовать уже подготовленный для вас форматер в Date+Extensions. 

Сейчас это не критично, но помните, что создание форматтера довольно дорогая операция и вызывать ее каждый раз, когда нам нужно сформировать новую строчку – не очень оптимально. Подробнее [здесь](https://sarunw.com/posts/how-expensive-is-dateformatter/)

2022-08-08 17:46 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    private func showNextQuestionOrResults() {
```suggestion
    }
    
    private func showNextQuestionOrResults() {
```

Не забывайте оставлять немного пространства между блоками кода, так его легче воспринимать

2022-08-08 17:46 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    QuizeQuestion(image: "Deadpool_000", text: "Рейтинг этого фильма больше чем 6?", correctAnswer: true),
Такой картинки в asset каталоге нет :( показывается белый экран. Наверное стоит убрать, чтобы не выглядело сломанным.

2022-08-08 17:46 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        DispatchQueue.main.asyncAfter(deadline: .now() + 0.1) {
```suggestion
        DispatchQueue.main.asyncAfter(deadline: .now() + 1) {
```

По заданию, обновление должно происходить через секунду

2022-08-08 17:46 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        yesButton.isUserInteractionEnabled = false
Здорово! 

Как вариант здесь можно использовать свойство isEnabled

2022-08-27 18:36 UTC, ABashkirova commented
@snowsergo вы можете смерджить эту ветку в main? Так будет проще отслеживать изменения со следующей задачей.

2022-08-27 18:40 UTC, merged

2022-08-27 18:44 UTC, snowsergo commented
> 
готово, слил в main